# Generated by Django 4.2.11 on 2024-03-17 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('birth_year', models.SmallIntegerField(blank=True, null=True)),
                ('death_year', models.SmallIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'books_author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('download_count', models.IntegerField(blank=True, null=True)),
                ('gutenberg_id', models.IntegerField(blank=True, null=True)),
                ('media_type', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'books_book',
            },
        ),
        migrations.CreateModel(
            name='BookLanguage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'books_language',
            },
        ),
        migrations.CreateModel(
            name='BookShelf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'books_bookshelf',
            },
        ),
        migrations.CreateModel(
            name='BookSubject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'books_subject',
            },
        ),
        migrations.CreateModel(
            name='BookFormat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mime_type', models.CharField(max_length=32)),
                ('url', models.CharField(max_length=256)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookformats', to='api.book')),
            ],
            options={
                'db_table': 'books_format',
            },
        ),
        migrations.CreateModel(
            name='BookBookSubject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookbooksubjects', to='api.booksubject')),
            ],
            options={
                'db_table': 'books_book_subjects',
            },
        ),
        migrations.CreateModel(
            name='BookBookShelves',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('bookshelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookbookshelves', to='api.bookshelf')),
            ],
            options={
                'db_table': 'books_book_bookshelves',
            },
        ),
        migrations.CreateModel(
            name='BookBookLanguage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_book_languages', to='api.booklanguage')),
            ],
            options={
                'db_table': 'books_book_languages',
            },
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='api.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
            ],
            options={
                'db_table': 'books_book_authors',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', through='api.BookAuthor', to='api.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(through='api.BookBookLanguage', to='api.booklanguage'),
        ),
        migrations.AddField(
            model_name='book',
            name='shelfs',
            field=models.ManyToManyField(through='api.BookBookShelves', to='api.bookshelf'),
        ),
        migrations.AddField(
            model_name='book',
            name='subjects',
            field=models.ManyToManyField(through='api.BookBookSubject', to='api.booksubject'),
        ),
    ]
